#!/bin/bash

# ---------------------------------------------
# 1. Definitions
# ---------------------------------------------
# Source directory containing config files
SOURCE_DIR="$(pwd)/RubberDuck/rc"

# Target directory where configs will be deployed
TARGET_DIR="$HOME/"

# ---------------------------------------------
# 2. Copy RC files to target
# ---------------------------------------------
echo -e "${NORD_YELLOW}Copying config files to target directory...${RESET}"
cp -a "$SOURCE_DIR/." "$TARGET_DIR/"


# ---------------------------------------------
# 3. Finish
# ---------------------------------------------
echo -e "${NORD_YELLOW}Config deployment completed successfully! $ ${RESET}"

